# Generated by Django 3.1.4 on 2020-12-27 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'liked_post',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('post_text', models.TextField()),
                ('post_date', models.DateTimeField()),
                ('post_likes', models.IntegerField()),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_mail', models.CharField(max_length=35)),
                ('user_password', models.CharField(max_length=100)),
                ('user_company', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.AddField(
            model_name='post',
            name='post_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sn.user'),
        ),
        migrations.AddField(
            model_name='likedpost',
            name='liked_post_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sn.post'),
        ),
        migrations.AddField(
            model_name='likedpost',
            name='liked_post_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sn.user'),
        ),
    ]
