# Generated by Django 3.1.4 on 2020-12-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sn', '0002_auto_20201228_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_clearbit_com',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_hunter_io',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
