# Generated by Django 3.1.4 on 2020-12-28 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sn', '0003_auto_20201228_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_online',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
