# Generated by Django 3.1.4 on 2021-01-01 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sn', '0004_user_user_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisLikedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disliked_post_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sn.post')),
                ('disliked_post_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sn.user')),
            ],
            options={
                'db_table': 'disliked_post',
            },
        ),
    ]
